# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 06:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPolicyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
